name: Bug report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value:  Thank you for contributing to Litex-CNC! âœŠ

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please explain what you're seeing and what you would expect to see.

        Please provide as much detail as possible to make understanding and solving your problem as quick as possible. ðŸ™
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Code
      description: >
        If applicable, please add a self-contained,
        [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example)
        demonstrating the bug. Also, when available, please share your configuration file and HAL-file
        as attachment to the issue.

      placeholder: |
        
        ...
      render: Python
  
  - type: checkboxes
    id: FPGA
    attributes:
      label: Which FPGA are you using
      description: |
        Which FPGA-card are you using? This information is vital when certain pins are not working,
        or when timing constraints are not met.
      options:
        - label: 5A-75B
        - label: 5A-75E
        - label: 5A-75B / HUB75HAT
        - label: other (please specify in issue)
    validations:
      required: true
          
  - type: textarea
    id: version
    attributes:
      label: Python, Litex-CNC and LinuxCNC & OS Version
      description: |
        Which version of Python, Litex-CNC and LinuxCNC are you using, and which Operating System?

        Please run the following command and copy the output below:

        ```bash
        python -c "import litexcnc;print(litexcnc.modules.__version__ )"
        dpkg -l linuxcnc
        lsb_release -a
        ```
        
      render: Text
    validations:
      required: true
