/********************************************************************
* Description:  encoder.c
*               A Litex-CNC component that canm be used to measure 
*               position by counting the pulses generated by a 
*               quadrature encoder. 
*
* Author: Peter van Tol <petertgvantol AT gmail DOT com>
* License: GPL Version 2
*    
* Copyright (c) 2022 All rights reserved.
*
********************************************************************/

/** This program is free software; you can redistribute it and/or
    modify it under the terms of version 2 of the GNU General
    Public License as published by the Free Software Foundation.
    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

    THE AUTHORS OF THIS LIBRARY ACCEPT ABSOLUTELY NO LIABILITY FOR
    ANY HARM OR LOSS RESULTING FROM ITS USE.  IT IS _EXTREMELY_ UNWISE
    TO RELY ON SOFTWARE ALONE FOR SAFETY.  Any machinery capable of
    harming persons must have provisions for completely removing power
    from all motors, etc, before persons enter any danger area.  All
    machinery must be designed to comply with local and national safety
    codes, and the authors of this software can not, and do not, take
    any responsibility for such compliance.

    This code was written as part of the LiteX-CNC project.
*/


int litexcnc_encoder_init(litexcnc_t *litexcnc, json_object *config) {

}


uint8_t litexcnc_encoder_prepare_write(litexcnc_t *litexcnc, uint8_t **data, long period) {
    /* This function is deliberately left empty, as no data regarding encoders
     * is send to the FPGA. It has been chosen to leave this function in place
     * for future enhancements and for similarity with the other components.
     */ 

}


uint8_t litexcnc_encoder_process_read(litexcnc_t *litexcnc, uint8_t** data, long period) {
    /* This function stores the raw counts as returned by the FPGA in raw_counts 
     * calculates based on this count the position and speeds. 
     */

     // Process all instances
    for (size_t i=0; i < litexcnc->encoder.num_instances; i++) {
        // Read the data and store it on the instance
        

    }


}